baseURL: http://localhost
languageCode: zh-CN
title: hugo theme
theme: hugo-theme
sectionPagesMenu: section

build:
  useResourceCacheWhen: fallback
  writeStats: true
  noJSConfigInAssets: true

#  https://gohugo.io/getting-started/configuration/#prose
caches:
  assets:
    dir: :resourceDir/_gen
    maxAge: 0