baseURL: http://localhost/dev
languageCode: zh-CN
title: Simple Tailwind Docs
theme: simple-tailwind-docs
sectionPagesMenu: section

build:
  useResourceCacheWhen: fallback
  writeStats: true
  noJSConfigInAssets: true

#  https://gohugo.io/getting-started/configuration/#prose
caches:
  assets:
    dir: :resourceDir/_gen
    maxAge: 0
  images:
    dir: :resourceDir/_gen
    maxAge: -1
